swagger:
  groupName: GroupName
  title: ApiTitle
  description: This is a sample
  termsOfServiceUrl:
  version: 0.0.2
  contactName: wangyuheng
  contactUrl: crick.wang
  contactEmail: wangyuheng@outlook.com
  paths: /upload.*, /category.*
  license:
  licenseUrl:
